### ISSUE TITLE
Please upload version 1.4.1 to CRAN

### ISSUE THREAD

**Issue by jranke** [bgreenwell/investr#46] opened 2022-03-23 09:07 UTC
In fact, investr has been archived... Could you upload a new version to CRAN? It's a pity that investr is not there any more. According to the [CRAN checks](https://cran-archive.r-project.org/web/checks/2022/2022-03-20_check_results_investr.html), there was a problem on R-devel, but currently, checking investr 1.4.1 on R-devel is fine.

**Comment by bgreenwell** [comment] 2022-03-23 13:40
Yikes, looks like I missed the initial email alert from CRAN weeks ago. I’ll try to get an update to CRAN by this weekend. Thanks for the note @jranke!

**Comment by jranke** [comment] 2022-03-23 15:17
OK, cool, then I can keep investr in my `Suggests:` (I am using it in unit tests to compare to results obtained with chemCal) without `Additional_repositories:`.

**Comment by jranke** [comment] 2022-03-28 07:15
Hi @bgreenwell, do you still plan to upload soon? I need to get a revised version of chemCal to CRAN, and I need to know if I can assume `investr` to be on CRAN.

**Comment by bgreenwell** [comment] 2022-03-28 14:46
Hi @jranke, I have ran the revised version through tests on r-winbuilder and on r-hub, but am unable to reproduce the original error from CRAN regarding r-devel (perhaps it was fixed?). In any case, I plan to upload 1.4.1 to CRAN by this evening.

**Comment by jranke** [comment] 2022-03-28 14:59
I tested you current master and could not reproduce the error either. I think there were some changes in nls that were later reverted, so it could be that your problem was only against an intermediate r-devel version. Anyways, good luck with your upload! If you close the issue after publication of the new version, I will know that it worked. Thanks!

**Comment by bgreenwell** [comment] 2022-03-29 01:17
Version 1.4.1 uploaded to CRAN 🤞. Might take a couple of days since ORPHANED packages get flagged as new submissions (I think). Assuming no issues, I’ll close this once it goes through successfully.

**Comment by jranke** [comment] 2022-03-29 01:29
OK, thanks for the update!

**Comment by bgreenwell** [comment] 2022-03-31 12:15
On CRAN now. Thanks for your patience @jranke!

**Closed by bgreenwell** 2022-03-31 12:16 UTC

**Comment by jranke** [comment] 2022-03-31 16:40
Sure thing! BTW, I think you should push your latest changes to github as well :) The DESCRIPTION is still at 1.4.1.9000 while we have 1.4.2 on CRAN.
